server {
    listen 8080;
    server_name _;

    default_type text/html;
    charset utf-8;
    root /usr/share/nginx/html;

    location = /health {
        default_type application/json;
        return 200 '{"status":"ok","app":"a01-idor-profil-user"}';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
